$\textbf{Jupyter Notebook and Numpy Tutorial}$
<br>
$\frac{Jupyter \ also \ supports \ Latex}{Which  \ is \ very \ usefull}$



In [7]:
import numpy as np

Numpy is a python library provides a lot of matlab like behavior (the most important behavior being the matrix opperations and speed)
<br>
The most important thing to consider is the the fundamental numpy data type, the numpy array (explain how it is preallocated and typed and very fast)
<br>
The first properties that I would like us to consider are shape and data type (from [Here](https://www.google.com/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&cad=rja&uact=8&ved=2ahUKEwilvODqtpXcAhW3GDQIHYtyC70QjRx6BAgBEAU&url=https%3A%2F%2Fwww.safaribooksonline.com%2Flibrary%2Fview%2Felegant-scipy%2F9781491922927%2Fch01.html&psig=AOvVaw2Z2m_p7p6BjMc3JE1qgTgf&ust=1531342563178360))
![numpy array indexing](https://www.safaribooksonline.com/library/view/elegant-scipy/9781491922927/assets/elsp_0105.png)


In [8]:
#for example lets do some linear algebra
oneD = np.zeros((10000,), dtype=np.float32)
print(oneD.shape)
twoD = oneD.reshape(np.int(np.sqrt(oneD.shape[0])),np.int(np.sqrt(oneD.shape[0])))
print(twoD.shape)
twoD[:,0] = 1
print(twoD)
#potential pitfall
print(oneD)
#if you actuall wanted to copy them to sepperately
oneD = np.zeros((10000,), dtype=np.float32)
twoD = np.copy(oneD.reshape(np.int(np.sqrt(oneD.shape[0])),np.int(np.sqrt(oneD.shape[0]))))

(10000,)
(100, 100)
[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]]
[1. 0. 0. ... 0. 0. 0.]


Since numpy is mostly written in C almost anything that you can do with numpy functions will be faster than doing the same with pure python functions. 
I think that this a good resource: https://www.python-course.eu/numpy.php